language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # We did all of that just so that we ccould conda install pymc:
  - conda install -c https://conda.binstar.org/pymc pymc
  # Now we install all the rest of our python dependencies:
  - pip install -r requirements.txt
  - pip install coveralls
  # Finally we set up SLTimer:
  - source setup/setup.sh

script:
  - nosetests -s --with-coverage --cover-package=desc.sltimer

after_success:
  - coveralls
